spring.application.name=GolfVejr.dk

# H2 Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/db
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# MySQL configuration - REPLACE WITH OWN DB
#spring.datasource.url=jdbc:mysql://localhost:3306/testdb
#spring.datasource.username=root
#spring.datasource.password=test
#spring.jpa.hibernate.ddl-auto=create
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
